export interface CreateBuildingListing {
    "name": string,
    "category": string,
    "description": string,
    "buildingType": string,
    "tags": Array<string>,
    "bedrooms": number | any,
    "livingSpace": number | any,
    "kitchen": number | any,
    "bathroom": number | any,
    "squareFoot": number | any,
    "lotSize": number | any,
    "floors": number | any,
    "features": Array<string>,
    "parkingSpace": Array<string>,
    "outdoorSpace": Array<string>,
    "heatingAndCooling": Array<string>,
    "energyEfficiency": Array<string>,
    "security": Array<string>,
    "yearOfConstruction": string,
    "condition": string,
    "communityAmenities": Array<string>,
    "publicTransport": Array<string>,
    "shellFinishedPrice": number | any,
    "finishedPrice": number | any,
    initalPaymentPercentage: number | any,
    "level1": number | any,
    "level2": number | any,
    "level3": number | any,
    "media": Array<string>,
    "address": string,
    "lga": string,
    "city": string,
    "state": string,
    "country": string,
    "adminId": number | any,
    "isDraft": boolean
}

export interface IPlots {
    "id": number | any,
    "propertyId": number | any,
    "plotSize": string,
    "price": number | any,
    "status": string,
    "createdAt": string,
    "updatedAt": string,
    "deleted": boolean
}

export interface IBuildingListingData {
    plots?: Array<IPlots>,
    property: IProperty;
}

export interface IProperty {
    "id": number | any,
    "name": string,
    "category": string,
    "description": string,
    "topography": string,
    "buildingType": string,
    "tags": Array<string>,
    "bedrooms": string,
    "livingSpace": string,
    "kitchen": string,
    "bathroom": string,
    "squareFoot": string,
    "lotSize": string,
    "floors": string,
    "features": Array<string>,
    "parkingSpace": Array<string>,
    "outdoorSpace": Array<string>,
    "heatingAndCooling": Array<string>,
    "energyEfficiency": Array<string>,
    "security": Array<string>,
    "yearOfConstruction": string,
    "condition": string,
    "communityAmenities": Array<string>,
    "publicTransport": Array<string>,
    "documents": Array<string>,
    "shellFinishedPrice": string,
    "finishedPrice": string,
    "buildingRestrictions": string,
    "developmentRestriction": Array<string>,
    "plots": number | any,
    "media": Array<string> | any,
    "rating": number | any,
    "gisData": "{}",
    "geolocation": string,
    "hasCourtCase": boolean,
    "isEncumbered": boolean,
    "approved": boolean,
    "isSoldOut": boolean,
    "isReserved": boolean,
    "address": string,
    "lga": string,
    "city": string,
    "state": string,
    "country": string,
    "uploadedByAdmin": true,
    "agentId": string,
    "adminId": number | any,
    "status": string,
    "isDraft": boolean,
    "isDeleted": boolean,
    "deletedAt": string,
    "createdBy": string,
    "createdAt": string,
    "updatedAt": string,
    level1: number,
    level2: number,
    level3: number,
    initalPaymentPercentage: number | any,
}

export interface CreateLandListing {
    "name": string,
    "category": "LAND",
    "description": string,
    "topography": string,
    "tags": Array<string>,
    "features": Array<string>,
    "communityAmenities": Array<string>,
    "publicTransport": Array<string>,
    "buildingRestrictions": Array<string>,
    "developmentRestriction": Array<string>,
    "plots": Array<any>,
    "media": Array<string>,
    "gisData": any,
    "address": string,
    "lga": string,
    "city": string,
    "state": string,
    "country": string,
    "adminId": number | any,
    "isDraft": boolean,
    initalPaymentPercentage: number | any,
    "level1": number | any,
    "level2": number | any,
    "level3": number | any,
}

export interface IBuildind {
    "id": number,
    "name": string,
    "description": string,
    "status": string,
    "tags": Array<string>,
    "state": string,
    "country": string,
    "rating": number,
    "hasCourtCase": boolean,
    "isEncumbered": boolean,
    "approved": boolean,
    "isSoldOut": boolean,
    "isReserved": boolean,
    "geolocation": any,
    "media": Array<string>,
    "documents": Array<string>,
    "gisData": any,
    "createdAt": string,
    "updatedAt": string,
    "deletedAt": any,
    "address": string,
    "adminId": number,
    "agentId": any,
    "bathroom": any,
    "bedrooms": any,
    "category": string,
    "city": string,
    "communityAmenities": Array<string>,
    "condition": any,
    "createdBy": any,
    "developmentRestriction": Array<string>,
    "energyEfficiency":Array<string>,
    "features": Array<string>,
    "finishedPrice": any,
    "floors": any,
    "heatingAndCooling": Array<string>,
    "isDeleted": false,
    "isDraft": false,
    "kitchen": any,
    "lga": string,
    "livingSpace": any,
    "lotSize": any,
    "parkingSpace": Array<string>,
    "plots": number,
    "publicTransport": Array<string>,
    "security": Array<string>,
    "shellFinishedPrice": any,
    "squareFoot": any,
    "topography": any,
    "uploadedByAdmin": boolean,
    "yearOfConstruction": any,
    "buildingType": any,
    "outdoorSpace": Array<string>,
    "buildingRestrictions": Array<string>,
    "initalPaymentPercentage": number,
    "level1": number,
    "level2": number,
    "level3": number,
    "Plot": Array<IPlots>
}