/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as HomeImport } from './routes/home'
import { Route as DashboardImport } from './routes/dashboard'
import { Route as DashboardIndexImport } from './routes/dashboard/index'
import { Route as DashboardSettingsImport } from './routes/dashboard/settings'
import { Route as DashboardReportsImport } from './routes/dashboard/reports'
import { Route as DashboardMaterialsImport } from './routes/dashboard/materials'
import { Route as DashboardHomeImport } from './routes/dashboard/home'
import { Route as AuthVerifyImport } from './routes/auth/verify'
import { Route as AuthLoginImport } from './routes/auth/login'
import { Route as AuthInviteImport } from './routes/auth/invite'
import { Route as DashboardWalletAlltransactionImport } from './routes/dashboard/wallet/alltransaction'
import { Route as DashboardUsersClientsIndexImport } from './routes/dashboard/users/clients/index'
import { Route as DashboardPropertyScheduleIndexImport } from './routes/dashboard/property/schedule/index'
import { Route as DashboardPropertySalesIndexImport } from './routes/dashboard/property/sales/index'
import { Route as DashboardPropertyListingsIndexImport } from './routes/dashboard/property/listings/index'
import { Route as DashboardPropertyInvestmentsIndexImport } from './routes/dashboard/property/investments/index'
import { Route as DashboardConstructionsProposalsIndexImport } from './routes/dashboard/constructions/proposals/index'
import { Route as DashboardUsersClientsDetailsImport } from './routes/dashboard/users/clients/details'
import { Route as DashboardPropertySalesDetailsImport } from './routes/dashboard/property/sales/details'
import { Route as DashboardPropertyListingsTransactionImport } from './routes/dashboard/property/listings/transaction'
import { Route as DashboardPropertyListingsDetailsImport } from './routes/dashboard/property/listings/details'
import { Route as DashboardPropertyListingsCreateLandImport } from './routes/dashboard/property/listings/create-land'
import { Route as DashboardPropertyListingsCreateBuildingImport } from './routes/dashboard/property/listings/create-building'
import { Route as DashboardPropertyInvestmentsDetailsImport } from './routes/dashboard/property/investments/details'
import { Route as DashboardConstructionsProposalsListingdetailsImport } from './routes/dashboard/constructions/proposals/listingdetails'
import { Route as DashboardConstructionsProposalsDetailsImport } from './routes/dashboard/constructions/proposals/details'

// Create Virtual Routes

const AboutLazyImport = createFileRoute('/about')()
const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const AboutLazyRoute = AboutLazyImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/about.lazy').then((d) => d.Route))

const HomeRoute = HomeImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRoute,
} as any)

const DashboardRoute = DashboardImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRoute,
} as any)

const IndexLazyRoute = IndexLazyImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const DashboardIndexRoute = DashboardIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)

const DashboardSettingsRoute = DashboardSettingsImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)

const DashboardReportsRoute = DashboardReportsImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => DashboardRoute,
} as any)

const DashboardMaterialsRoute = DashboardMaterialsImport.update({
  id: '/materials',
  path: '/materials',
  getParentRoute: () => DashboardRoute,
} as any)

const DashboardHomeRoute = DashboardHomeImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => DashboardRoute,
} as any)

const AuthVerifyRoute = AuthVerifyImport.update({
  id: '/auth/verify',
  path: '/auth/verify',
  getParentRoute: () => rootRoute,
} as any)

const AuthLoginRoute = AuthLoginImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRoute,
} as any)

const AuthInviteRoute = AuthInviteImport.update({
  id: '/auth/invite',
  path: '/auth/invite',
  getParentRoute: () => rootRoute,
} as any)

const DashboardWalletAlltransactionRoute =
  DashboardWalletAlltransactionImport.update({
    id: '/wallet/alltransaction',
    path: '/wallet/alltransaction',
    getParentRoute: () => DashboardRoute,
  } as any)

const DashboardUsersClientsIndexRoute = DashboardUsersClientsIndexImport.update(
  {
    id: '/users/clients/',
    path: '/users/clients/',
    getParentRoute: () => DashboardRoute,
  } as any,
)

const DashboardPropertyScheduleIndexRoute =
  DashboardPropertyScheduleIndexImport.update({
    id: '/property/schedule/',
    path: '/property/schedule/',
    getParentRoute: () => DashboardRoute,
  } as any)

const DashboardPropertySalesIndexRoute =
  DashboardPropertySalesIndexImport.update({
    id: '/property/sales/',
    path: '/property/sales/',
    getParentRoute: () => DashboardRoute,
  } as any)

const DashboardPropertyListingsIndexRoute =
  DashboardPropertyListingsIndexImport.update({
    id: '/property/listings/',
    path: '/property/listings/',
    getParentRoute: () => DashboardRoute,
  } as any)

const DashboardPropertyInvestmentsIndexRoute =
  DashboardPropertyInvestmentsIndexImport.update({
    id: '/property/investments/',
    path: '/property/investments/',
    getParentRoute: () => DashboardRoute,
  } as any)

const DashboardConstructionsProposalsIndexRoute =
  DashboardConstructionsProposalsIndexImport.update({
    id: '/constructions/proposals/',
    path: '/constructions/proposals/',
    getParentRoute: () => DashboardRoute,
  } as any)

const DashboardUsersClientsDetailsRoute =
  DashboardUsersClientsDetailsImport.update({
    id: '/users/clients/details',
    path: '/users/clients/details',
    getParentRoute: () => DashboardRoute,
  } as any)

const DashboardPropertySalesDetailsRoute =
  DashboardPropertySalesDetailsImport.update({
    id: '/property/sales/details',
    path: '/property/sales/details',
    getParentRoute: () => DashboardRoute,
  } as any)

const DashboardPropertyListingsTransactionRoute =
  DashboardPropertyListingsTransactionImport.update({
    id: '/property/listings/transaction',
    path: '/property/listings/transaction',
    getParentRoute: () => DashboardRoute,
  } as any)

const DashboardPropertyListingsDetailsRoute =
  DashboardPropertyListingsDetailsImport.update({
    id: '/property/listings/details',
    path: '/property/listings/details',
    getParentRoute: () => DashboardRoute,
  } as any)

const DashboardPropertyListingsCreateLandRoute =
  DashboardPropertyListingsCreateLandImport.update({
    id: '/property/listings/create-land',
    path: '/property/listings/create-land',
    getParentRoute: () => DashboardRoute,
  } as any)

const DashboardPropertyListingsCreateBuildingRoute =
  DashboardPropertyListingsCreateBuildingImport.update({
    id: '/property/listings/create-building',
    path: '/property/listings/create-building',
    getParentRoute: () => DashboardRoute,
  } as any)

const DashboardPropertyInvestmentsDetailsRoute =
  DashboardPropertyInvestmentsDetailsImport.update({
    id: '/property/investments/details',
    path: '/property/investments/details',
    getParentRoute: () => DashboardRoute,
  } as any)

const DashboardConstructionsProposalsListingdetailsRoute =
  DashboardConstructionsProposalsListingdetailsImport.update({
    id: '/constructions/proposals/listingdetails',
    path: '/constructions/proposals/listingdetails',
    getParentRoute: () => DashboardRoute,
  } as any)

const DashboardConstructionsProposalsDetailsRoute =
  DashboardConstructionsProposalsDetailsImport.update({
    id: '/constructions/proposals/details',
    path: '/constructions/proposals/details',
    getParentRoute: () => DashboardRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardImport
      parentRoute: typeof rootRoute
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutLazyImport
      parentRoute: typeof rootRoute
    }
    '/auth/invite': {
      id: '/auth/invite'
      path: '/auth/invite'
      fullPath: '/auth/invite'
      preLoaderRoute: typeof AuthInviteImport
      parentRoute: typeof rootRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginImport
      parentRoute: typeof rootRoute
    }
    '/auth/verify': {
      id: '/auth/verify'
      path: '/auth/verify'
      fullPath: '/auth/verify'
      preLoaderRoute: typeof AuthVerifyImport
      parentRoute: typeof rootRoute
    }
    '/dashboard/home': {
      id: '/dashboard/home'
      path: '/home'
      fullPath: '/dashboard/home'
      preLoaderRoute: typeof DashboardHomeImport
      parentRoute: typeof DashboardImport
    }
    '/dashboard/materials': {
      id: '/dashboard/materials'
      path: '/materials'
      fullPath: '/dashboard/materials'
      preLoaderRoute: typeof DashboardMaterialsImport
      parentRoute: typeof DashboardImport
    }
    '/dashboard/reports': {
      id: '/dashboard/reports'
      path: '/reports'
      fullPath: '/dashboard/reports'
      preLoaderRoute: typeof DashboardReportsImport
      parentRoute: typeof DashboardImport
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsImport
      parentRoute: typeof DashboardImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexImport
      parentRoute: typeof DashboardImport
    }
    '/dashboard/wallet/alltransaction': {
      id: '/dashboard/wallet/alltransaction'
      path: '/wallet/alltransaction'
      fullPath: '/dashboard/wallet/alltransaction'
      preLoaderRoute: typeof DashboardWalletAlltransactionImport
      parentRoute: typeof DashboardImport
    }
    '/dashboard/constructions/proposals/details': {
      id: '/dashboard/constructions/proposals/details'
      path: '/constructions/proposals/details'
      fullPath: '/dashboard/constructions/proposals/details'
      preLoaderRoute: typeof DashboardConstructionsProposalsDetailsImport
      parentRoute: typeof DashboardImport
    }
    '/dashboard/constructions/proposals/listingdetails': {
      id: '/dashboard/constructions/proposals/listingdetails'
      path: '/constructions/proposals/listingdetails'
      fullPath: '/dashboard/constructions/proposals/listingdetails'
      preLoaderRoute: typeof DashboardConstructionsProposalsListingdetailsImport
      parentRoute: typeof DashboardImport
    }
    '/dashboard/property/investments/details': {
      id: '/dashboard/property/investments/details'
      path: '/property/investments/details'
      fullPath: '/dashboard/property/investments/details'
      preLoaderRoute: typeof DashboardPropertyInvestmentsDetailsImport
      parentRoute: typeof DashboardImport
    }
    '/dashboard/property/listings/create-building': {
      id: '/dashboard/property/listings/create-building'
      path: '/property/listings/create-building'
      fullPath: '/dashboard/property/listings/create-building'
      preLoaderRoute: typeof DashboardPropertyListingsCreateBuildingImport
      parentRoute: typeof DashboardImport
    }
    '/dashboard/property/listings/create-land': {
      id: '/dashboard/property/listings/create-land'
      path: '/property/listings/create-land'
      fullPath: '/dashboard/property/listings/create-land'
      preLoaderRoute: typeof DashboardPropertyListingsCreateLandImport
      parentRoute: typeof DashboardImport
    }
    '/dashboard/property/listings/details': {
      id: '/dashboard/property/listings/details'
      path: '/property/listings/details'
      fullPath: '/dashboard/property/listings/details'
      preLoaderRoute: typeof DashboardPropertyListingsDetailsImport
      parentRoute: typeof DashboardImport
    }
    '/dashboard/property/listings/transaction': {
      id: '/dashboard/property/listings/transaction'
      path: '/property/listings/transaction'
      fullPath: '/dashboard/property/listings/transaction'
      preLoaderRoute: typeof DashboardPropertyListingsTransactionImport
      parentRoute: typeof DashboardImport
    }
    '/dashboard/property/sales/details': {
      id: '/dashboard/property/sales/details'
      path: '/property/sales/details'
      fullPath: '/dashboard/property/sales/details'
      preLoaderRoute: typeof DashboardPropertySalesDetailsImport
      parentRoute: typeof DashboardImport
    }
    '/dashboard/users/clients/details': {
      id: '/dashboard/users/clients/details'
      path: '/users/clients/details'
      fullPath: '/dashboard/users/clients/details'
      preLoaderRoute: typeof DashboardUsersClientsDetailsImport
      parentRoute: typeof DashboardImport
    }
    '/dashboard/constructions/proposals/': {
      id: '/dashboard/constructions/proposals/'
      path: '/constructions/proposals'
      fullPath: '/dashboard/constructions/proposals'
      preLoaderRoute: typeof DashboardConstructionsProposalsIndexImport
      parentRoute: typeof DashboardImport
    }
    '/dashboard/property/investments/': {
      id: '/dashboard/property/investments/'
      path: '/property/investments'
      fullPath: '/dashboard/property/investments'
      preLoaderRoute: typeof DashboardPropertyInvestmentsIndexImport
      parentRoute: typeof DashboardImport
    }
    '/dashboard/property/listings/': {
      id: '/dashboard/property/listings/'
      path: '/property/listings'
      fullPath: '/dashboard/property/listings'
      preLoaderRoute: typeof DashboardPropertyListingsIndexImport
      parentRoute: typeof DashboardImport
    }
    '/dashboard/property/sales/': {
      id: '/dashboard/property/sales/'
      path: '/property/sales'
      fullPath: '/dashboard/property/sales'
      preLoaderRoute: typeof DashboardPropertySalesIndexImport
      parentRoute: typeof DashboardImport
    }
    '/dashboard/property/schedule/': {
      id: '/dashboard/property/schedule/'
      path: '/property/schedule'
      fullPath: '/dashboard/property/schedule'
      preLoaderRoute: typeof DashboardPropertyScheduleIndexImport
      parentRoute: typeof DashboardImport
    }
    '/dashboard/users/clients/': {
      id: '/dashboard/users/clients/'
      path: '/users/clients'
      fullPath: '/dashboard/users/clients'
      preLoaderRoute: typeof DashboardUsersClientsIndexImport
      parentRoute: typeof DashboardImport
    }
  }
}

// Create and export the route tree

interface DashboardRouteChildren {
  DashboardHomeRoute: typeof DashboardHomeRoute
  DashboardMaterialsRoute: typeof DashboardMaterialsRoute
  DashboardReportsRoute: typeof DashboardReportsRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardWalletAlltransactionRoute: typeof DashboardWalletAlltransactionRoute
  DashboardConstructionsProposalsDetailsRoute: typeof DashboardConstructionsProposalsDetailsRoute
  DashboardConstructionsProposalsListingdetailsRoute: typeof DashboardConstructionsProposalsListingdetailsRoute
  DashboardPropertyInvestmentsDetailsRoute: typeof DashboardPropertyInvestmentsDetailsRoute
  DashboardPropertyListingsCreateBuildingRoute: typeof DashboardPropertyListingsCreateBuildingRoute
  DashboardPropertyListingsCreateLandRoute: typeof DashboardPropertyListingsCreateLandRoute
  DashboardPropertyListingsDetailsRoute: typeof DashboardPropertyListingsDetailsRoute
  DashboardPropertyListingsTransactionRoute: typeof DashboardPropertyListingsTransactionRoute
  DashboardPropertySalesDetailsRoute: typeof DashboardPropertySalesDetailsRoute
  DashboardUsersClientsDetailsRoute: typeof DashboardUsersClientsDetailsRoute
  DashboardConstructionsProposalsIndexRoute: typeof DashboardConstructionsProposalsIndexRoute
  DashboardPropertyInvestmentsIndexRoute: typeof DashboardPropertyInvestmentsIndexRoute
  DashboardPropertyListingsIndexRoute: typeof DashboardPropertyListingsIndexRoute
  DashboardPropertySalesIndexRoute: typeof DashboardPropertySalesIndexRoute
  DashboardPropertyScheduleIndexRoute: typeof DashboardPropertyScheduleIndexRoute
  DashboardUsersClientsIndexRoute: typeof DashboardUsersClientsIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardHomeRoute: DashboardHomeRoute,
  DashboardMaterialsRoute: DashboardMaterialsRoute,
  DashboardReportsRoute: DashboardReportsRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardWalletAlltransactionRoute: DashboardWalletAlltransactionRoute,
  DashboardConstructionsProposalsDetailsRoute:
    DashboardConstructionsProposalsDetailsRoute,
  DashboardConstructionsProposalsListingdetailsRoute:
    DashboardConstructionsProposalsListingdetailsRoute,
  DashboardPropertyInvestmentsDetailsRoute:
    DashboardPropertyInvestmentsDetailsRoute,
  DashboardPropertyListingsCreateBuildingRoute:
    DashboardPropertyListingsCreateBuildingRoute,
  DashboardPropertyListingsCreateLandRoute:
    DashboardPropertyListingsCreateLandRoute,
  DashboardPropertyListingsDetailsRoute: DashboardPropertyListingsDetailsRoute,
  DashboardPropertyListingsTransactionRoute:
    DashboardPropertyListingsTransactionRoute,
  DashboardPropertySalesDetailsRoute: DashboardPropertySalesDetailsRoute,
  DashboardUsersClientsDetailsRoute: DashboardUsersClientsDetailsRoute,
  DashboardConstructionsProposalsIndexRoute:
    DashboardConstructionsProposalsIndexRoute,
  DashboardPropertyInvestmentsIndexRoute:
    DashboardPropertyInvestmentsIndexRoute,
  DashboardPropertyListingsIndexRoute: DashboardPropertyListingsIndexRoute,
  DashboardPropertySalesIndexRoute: DashboardPropertySalesIndexRoute,
  DashboardPropertyScheduleIndexRoute: DashboardPropertyScheduleIndexRoute,
  DashboardUsersClientsIndexRoute: DashboardUsersClientsIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/home': typeof HomeRoute
  '/about': typeof AboutLazyRoute
  '/auth/invite': typeof AuthInviteRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/verify': typeof AuthVerifyRoute
  '/dashboard/home': typeof DashboardHomeRoute
  '/dashboard/materials': typeof DashboardMaterialsRoute
  '/dashboard/reports': typeof DashboardReportsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/wallet/alltransaction': typeof DashboardWalletAlltransactionRoute
  '/dashboard/constructions/proposals/details': typeof DashboardConstructionsProposalsDetailsRoute
  '/dashboard/constructions/proposals/listingdetails': typeof DashboardConstructionsProposalsListingdetailsRoute
  '/dashboard/property/investments/details': typeof DashboardPropertyInvestmentsDetailsRoute
  '/dashboard/property/listings/create-building': typeof DashboardPropertyListingsCreateBuildingRoute
  '/dashboard/property/listings/create-land': typeof DashboardPropertyListingsCreateLandRoute
  '/dashboard/property/listings/details': typeof DashboardPropertyListingsDetailsRoute
  '/dashboard/property/listings/transaction': typeof DashboardPropertyListingsTransactionRoute
  '/dashboard/property/sales/details': typeof DashboardPropertySalesDetailsRoute
  '/dashboard/users/clients/details': typeof DashboardUsersClientsDetailsRoute
  '/dashboard/constructions/proposals': typeof DashboardConstructionsProposalsIndexRoute
  '/dashboard/property/investments': typeof DashboardPropertyInvestmentsIndexRoute
  '/dashboard/property/listings': typeof DashboardPropertyListingsIndexRoute
  '/dashboard/property/sales': typeof DashboardPropertySalesIndexRoute
  '/dashboard/property/schedule': typeof DashboardPropertyScheduleIndexRoute
  '/dashboard/users/clients': typeof DashboardUsersClientsIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/home': typeof HomeRoute
  '/about': typeof AboutLazyRoute
  '/auth/invite': typeof AuthInviteRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/verify': typeof AuthVerifyRoute
  '/dashboard/home': typeof DashboardHomeRoute
  '/dashboard/materials': typeof DashboardMaterialsRoute
  '/dashboard/reports': typeof DashboardReportsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/wallet/alltransaction': typeof DashboardWalletAlltransactionRoute
  '/dashboard/constructions/proposals/details': typeof DashboardConstructionsProposalsDetailsRoute
  '/dashboard/constructions/proposals/listingdetails': typeof DashboardConstructionsProposalsListingdetailsRoute
  '/dashboard/property/investments/details': typeof DashboardPropertyInvestmentsDetailsRoute
  '/dashboard/property/listings/create-building': typeof DashboardPropertyListingsCreateBuildingRoute
  '/dashboard/property/listings/create-land': typeof DashboardPropertyListingsCreateLandRoute
  '/dashboard/property/listings/details': typeof DashboardPropertyListingsDetailsRoute
  '/dashboard/property/listings/transaction': typeof DashboardPropertyListingsTransactionRoute
  '/dashboard/property/sales/details': typeof DashboardPropertySalesDetailsRoute
  '/dashboard/users/clients/details': typeof DashboardUsersClientsDetailsRoute
  '/dashboard/constructions/proposals': typeof DashboardConstructionsProposalsIndexRoute
  '/dashboard/property/investments': typeof DashboardPropertyInvestmentsIndexRoute
  '/dashboard/property/listings': typeof DashboardPropertyListingsIndexRoute
  '/dashboard/property/sales': typeof DashboardPropertySalesIndexRoute
  '/dashboard/property/schedule': typeof DashboardPropertyScheduleIndexRoute
  '/dashboard/users/clients': typeof DashboardUsersClientsIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexLazyRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/home': typeof HomeRoute
  '/about': typeof AboutLazyRoute
  '/auth/invite': typeof AuthInviteRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/verify': typeof AuthVerifyRoute
  '/dashboard/home': typeof DashboardHomeRoute
  '/dashboard/materials': typeof DashboardMaterialsRoute
  '/dashboard/reports': typeof DashboardReportsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/wallet/alltransaction': typeof DashboardWalletAlltransactionRoute
  '/dashboard/constructions/proposals/details': typeof DashboardConstructionsProposalsDetailsRoute
  '/dashboard/constructions/proposals/listingdetails': typeof DashboardConstructionsProposalsListingdetailsRoute
  '/dashboard/property/investments/details': typeof DashboardPropertyInvestmentsDetailsRoute
  '/dashboard/property/listings/create-building': typeof DashboardPropertyListingsCreateBuildingRoute
  '/dashboard/property/listings/create-land': typeof DashboardPropertyListingsCreateLandRoute
  '/dashboard/property/listings/details': typeof DashboardPropertyListingsDetailsRoute
  '/dashboard/property/listings/transaction': typeof DashboardPropertyListingsTransactionRoute
  '/dashboard/property/sales/details': typeof DashboardPropertySalesDetailsRoute
  '/dashboard/users/clients/details': typeof DashboardUsersClientsDetailsRoute
  '/dashboard/constructions/proposals/': typeof DashboardConstructionsProposalsIndexRoute
  '/dashboard/property/investments/': typeof DashboardPropertyInvestmentsIndexRoute
  '/dashboard/property/listings/': typeof DashboardPropertyListingsIndexRoute
  '/dashboard/property/sales/': typeof DashboardPropertySalesIndexRoute
  '/dashboard/property/schedule/': typeof DashboardPropertyScheduleIndexRoute
  '/dashboard/users/clients/': typeof DashboardUsersClientsIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/home'
    | '/about'
    | '/auth/invite'
    | '/auth/login'
    | '/auth/verify'
    | '/dashboard/home'
    | '/dashboard/materials'
    | '/dashboard/reports'
    | '/dashboard/settings'
    | '/dashboard/'
    | '/dashboard/wallet/alltransaction'
    | '/dashboard/constructions/proposals/details'
    | '/dashboard/constructions/proposals/listingdetails'
    | '/dashboard/property/investments/details'
    | '/dashboard/property/listings/create-building'
    | '/dashboard/property/listings/create-land'
    | '/dashboard/property/listings/details'
    | '/dashboard/property/listings/transaction'
    | '/dashboard/property/sales/details'
    | '/dashboard/users/clients/details'
    | '/dashboard/constructions/proposals'
    | '/dashboard/property/investments'
    | '/dashboard/property/listings'
    | '/dashboard/property/sales'
    | '/dashboard/property/schedule'
    | '/dashboard/users/clients'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/home'
    | '/about'
    | '/auth/invite'
    | '/auth/login'
    | '/auth/verify'
    | '/dashboard/home'
    | '/dashboard/materials'
    | '/dashboard/reports'
    | '/dashboard/settings'
    | '/dashboard'
    | '/dashboard/wallet/alltransaction'
    | '/dashboard/constructions/proposals/details'
    | '/dashboard/constructions/proposals/listingdetails'
    | '/dashboard/property/investments/details'
    | '/dashboard/property/listings/create-building'
    | '/dashboard/property/listings/create-land'
    | '/dashboard/property/listings/details'
    | '/dashboard/property/listings/transaction'
    | '/dashboard/property/sales/details'
    | '/dashboard/users/clients/details'
    | '/dashboard/constructions/proposals'
    | '/dashboard/property/investments'
    | '/dashboard/property/listings'
    | '/dashboard/property/sales'
    | '/dashboard/property/schedule'
    | '/dashboard/users/clients'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/home'
    | '/about'
    | '/auth/invite'
    | '/auth/login'
    | '/auth/verify'
    | '/dashboard/home'
    | '/dashboard/materials'
    | '/dashboard/reports'
    | '/dashboard/settings'
    | '/dashboard/'
    | '/dashboard/wallet/alltransaction'
    | '/dashboard/constructions/proposals/details'
    | '/dashboard/constructions/proposals/listingdetails'
    | '/dashboard/property/investments/details'
    | '/dashboard/property/listings/create-building'
    | '/dashboard/property/listings/create-land'
    | '/dashboard/property/listings/details'
    | '/dashboard/property/listings/transaction'
    | '/dashboard/property/sales/details'
    | '/dashboard/users/clients/details'
    | '/dashboard/constructions/proposals/'
    | '/dashboard/property/investments/'
    | '/dashboard/property/listings/'
    | '/dashboard/property/sales/'
    | '/dashboard/property/schedule/'
    | '/dashboard/users/clients/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  HomeRoute: typeof HomeRoute
  AboutLazyRoute: typeof AboutLazyRoute
  AuthInviteRoute: typeof AuthInviteRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthVerifyRoute: typeof AuthVerifyRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  DashboardRoute: DashboardRouteWithChildren,
  HomeRoute: HomeRoute,
  AboutLazyRoute: AboutLazyRoute,
  AuthInviteRoute: AuthInviteRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthVerifyRoute: AuthVerifyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/dashboard",
        "/home",
        "/about",
        "/auth/invite",
        "/auth/login",
        "/auth/verify"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/dashboard": {
      "filePath": "dashboard.tsx",
      "children": [
        "/dashboard/home",
        "/dashboard/materials",
        "/dashboard/reports",
        "/dashboard/settings",
        "/dashboard/",
        "/dashboard/wallet/alltransaction",
        "/dashboard/constructions/proposals/details",
        "/dashboard/constructions/proposals/listingdetails",
        "/dashboard/property/investments/details",
        "/dashboard/property/listings/create-building",
        "/dashboard/property/listings/create-land",
        "/dashboard/property/listings/details",
        "/dashboard/property/listings/transaction",
        "/dashboard/property/sales/details",
        "/dashboard/users/clients/details",
        "/dashboard/constructions/proposals/",
        "/dashboard/property/investments/",
        "/dashboard/property/listings/",
        "/dashboard/property/sales/",
        "/dashboard/property/schedule/",
        "/dashboard/users/clients/"
      ]
    },
    "/home": {
      "filePath": "home.tsx"
    },
    "/about": {
      "filePath": "about.lazy.tsx"
    },
    "/auth/invite": {
      "filePath": "auth/invite.tsx"
    },
    "/auth/login": {
      "filePath": "auth/login.tsx"
    },
    "/auth/verify": {
      "filePath": "auth/verify.tsx"
    },
    "/dashboard/home": {
      "filePath": "dashboard/home.tsx",
      "parent": "/dashboard"
    },
    "/dashboard/materials": {
      "filePath": "dashboard/materials.tsx",
      "parent": "/dashboard"
    },
    "/dashboard/reports": {
      "filePath": "dashboard/reports.tsx",
      "parent": "/dashboard"
    },
    "/dashboard/settings": {
      "filePath": "dashboard/settings.tsx",
      "parent": "/dashboard"
    },
    "/dashboard/": {
      "filePath": "dashboard/index.tsx",
      "parent": "/dashboard"
    },
    "/dashboard/wallet/alltransaction": {
      "filePath": "dashboard/wallet/alltransaction.tsx",
      "parent": "/dashboard"
    },
    "/dashboard/constructions/proposals/details": {
      "filePath": "dashboard/constructions/proposals/details.tsx",
      "parent": "/dashboard"
    },
    "/dashboard/constructions/proposals/listingdetails": {
      "filePath": "dashboard/constructions/proposals/listingdetails.tsx",
      "parent": "/dashboard"
    },
    "/dashboard/property/investments/details": {
      "filePath": "dashboard/property/investments/details.tsx",
      "parent": "/dashboard"
    },
    "/dashboard/property/listings/create-building": {
      "filePath": "dashboard/property/listings/create-building.tsx",
      "parent": "/dashboard"
    },
    "/dashboard/property/listings/create-land": {
      "filePath": "dashboard/property/listings/create-land.tsx",
      "parent": "/dashboard"
    },
    "/dashboard/property/listings/details": {
      "filePath": "dashboard/property/listings/details.tsx",
      "parent": "/dashboard"
    },
    "/dashboard/property/listings/transaction": {
      "filePath": "dashboard/property/listings/transaction.tsx",
      "parent": "/dashboard"
    },
    "/dashboard/property/sales/details": {
      "filePath": "dashboard/property/sales/details.tsx",
      "parent": "/dashboard"
    },
    "/dashboard/users/clients/details": {
      "filePath": "dashboard/users/clients/details.tsx",
      "parent": "/dashboard"
    },
    "/dashboard/constructions/proposals/": {
      "filePath": "dashboard/constructions/proposals/index.tsx",
      "parent": "/dashboard"
    },
    "/dashboard/property/investments/": {
      "filePath": "dashboard/property/investments/index.tsx",
      "parent": "/dashboard"
    },
    "/dashboard/property/listings/": {
      "filePath": "dashboard/property/listings/index.tsx",
      "parent": "/dashboard"
    },
    "/dashboard/property/sales/": {
      "filePath": "dashboard/property/sales/index.tsx",
      "parent": "/dashboard"
    },
    "/dashboard/property/schedule/": {
      "filePath": "dashboard/property/schedule/index.tsx",
      "parent": "/dashboard"
    },
    "/dashboard/users/clients/": {
      "filePath": "dashboard/users/clients/index.tsx",
      "parent": "/dashboard"
    }
  }
}
ROUTE_MANIFEST_END */
